name: Generate Snake Animation

on:
  schedule: # runs every 6 hours
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Snake Animation
        uses: actions/download-artifact@v2
        with:
          name: snake
          path: dist
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
